name: test-my-laravel-project

on:
  push:
    branches: [ main ]
    paths:
      - 'laravel_brief4_tests_unitaires/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  php_version: 8.2

jobs:
  test:
    runs-on: ubuntu-latest

    concurrency:
      group: test-my-laravel-project-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: pcov

      - name: Install Composer dependencies
        run: |
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist

      - name: Prepare SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --force

      - name: Seed database
        run: php artisan db:seed --force

      - name: Test
        run: php artisan test
